Astro 1760 close modal bugs
RocketCommunicationsInc/astro-components-stencil pull request #130
Opened 2021-08-12 18:58 UTC by NicDominguez

## Brief Description

Fixes a couple bugs where modal was not closing on enter key and outside click

## JIRA Link

[ASTRO-1760](https://rocketcom.atlassian.net/browse/ASTRO-1760)

## Motivation and Context

bugs = bad

## Types of changes

-   [X] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [X] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.

2021-08-12 21:32 UTC, Cheshire89 requested changes

2021-08-12 21:32 UTC, Cheshire89 commented on src/components/rux-modal/rux-modal.tsx
> +        console.log('handleClick called')
remove log please

2021-08-12 21:37 UTC, NicDominguez commented on src/components/rux-modal/rux-modal.tsx
> +        console.log('handleClick called')
I'm testing to check a difference in the local versus netlify deploy, it will be removed before merge

2021-08-13 13:02 UTC, markacianfrani approved these changes
can we add a test to cover this?

2021-08-16 16:50 UTC, Cheshire89 approved these changes

2021-08-16 16:51 UTC, merged