Astro 1670 form field tests
RocketCommunicationsInc/astro-components-stencil pull request #132
Opened 2021-08-12 21:33 UTC by Cheshire89

## Brief Description

Added e2e test for input field component

## JIRA Link

https://rocketcom.atlassian.net/browse/ASTRO-1670

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [x] I have added tests to cover my changes.

2021-08-13 13:05 UTC, markacianfrani approved these changes

2021-08-16 20:57 UTC, NicDominguez requested changes
A few of the tests that were async are passing because they are not running through the entire test. There are a few changes that need to be made to get them all to pass but overall your tests are very thorough.

2021-08-16 20:57 UTC, NicDominguez commented on src/tests/pages/form-input-field.html
> +                        value="Hello World"
should be ruxInput2

2021-08-16 20:57 UTC, NicDominguez commented on src/components/rux-input-field/test/rux-input-field.e2e.js
> +    it('submits the correct value when using a form', async () => {
remove async

2021-08-16 20:57 UTC, NicDominguez commented on src/components/rux-input-field/test/rux-input-field.e2e.js
> +    it('does not submit disabled even with value', async () => {
remove async

2021-08-16 20:57 UTC, NicDominguez commented on src/components/rux-input-field/test/rux-input-field.e2e.js
> +        cy.get('#ruxInput2').should('be.disabled')
This doesn't pass because the ruxInput host isn't disabled just the child input. Use `cy.get('#ruxInput2').should('have.attr', 'disabled', 'disabled')` to check if the host has the disabled attribute.

2021-08-16 20:57 UTC, NicDominguez commented on src/components/rux-input-field/test/rux-input-field.e2e.js
> +        cy.get('#log').children().its('length').should('eq', 2)
.should('eq', 4) since the log picks up ruxInput, nativeInput, ruxInput3, and nativeInput3

2021-08-16 20:57 UTC, NicDominguez commented on src/components/rux-input-field/test/rux-input-field.e2e.js
> +        cy.get('#log').should('not.contain', `nativeInput:${testString}`)
These are failing. My guess is the FormData is taking what has been typed into the input field rather than the value assigned to the  "value" attribute.

2021-08-16 20:57 UTC, NicDominguez commented on src/components/rux-input-field/test/rux-input-field.e2e.js
> +        cy.get('#log').children().its('length').should('eq', 2)
.should('eq', 4) since the log picks up ruxInput, nativeInput, ruxInput3, and nativeInput3

2021-08-16 20:57 UTC, NicDominguez commented on src/components/rux-input-field/rux-input-field.tsx
> +        renderHiddenInput(true, el, name, value, disabled)
Always a fan of this structure. Thank you for cleaning up the component.

2021-08-16 21:11 UTC, Cheshire89 commented on src/components/rux-input-field/test/rux-input-field.e2e.js
> +        cy.get('#log').should('not.contain', `nativeInput:${testString}`)
No because this
```
 beforeEach(() => {
        cy.visitForm('input-field')
    })
    ```
    loads fresh form for each of the `it` tests

2021-08-16 23:22 UTC, NicDominguez requested changes

2021-08-16 23:22 UTC, NicDominguez commented on src/components/rux-textarea/test/form-textarea.e2e.js
> +        cy.get('#formSumbitBtn').click()
I think the only thing you need to do to get this to pass is explicitly type the value you want into the field with .type(). The form data doesn't seem to be picking up the initial value declared by the value attribute.

2021-08-17 14:59 UTC, NicDominguez approved these changes
Nice!

2021-08-17 16:52 UTC, merged