Bug(rux-checkbox) - Add Imperative Logic
RocketCommunicationsInc/astro-components-stencil pull request #177
Opened 2021-08-30 20:00 UTC by Full-lifey

## Brief Description

rux-checkbox did not have any imperative logic wired up. If you changed checked or indeterminate props nothing happened

## JIRA Link

[ASTRO-1836](https://rocketcom.atlassian.net/browse/ASTRO-1836?atlOrigin=eyJpIjoiMjJmMTY2OWU0NDYxNDJlODk2YmM1NDg3YjM1ZTk4M2MiLCJwIjoiaiJ9)

## Related Issue

[ASTRO-1736](https://rocketcom.atlassian.net/browse/ASTRO-1736?atlOrigin=eyJpIjoiNmY4YTE4Njc5OTNjNDY0NTlmYWU1ODExMTA4YjM3ODgiLCJwIjoiaiJ9)

## General Notes

## Motivation and Context

Allows use of imperative logic within a given framework to update component state

## Issues and Limitations

## Types of changes

-   [x] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [x] I have added tests to cover my changes.

2021-08-30 23:09 UTC, markacianfrani commented on src/components/rux-checkbox/rux-checkbox.tsx
> +        this.ruxChange.emit({
Just a heads up, this would be considered a breaking change since rux-change no longer submits just a boolean. 

Why not just let the change event emit the host element and be listened to via `event.target.checked` or `event.target.indeterminate` rather than `event.detail.checked` ?

2021-08-31 00:08 UTC, markacianfrani commented
I don't think we actually should be changing the checked value.

https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type=checkbox)
https://css-tricks.com/indeterminate-checkboxes/

Indeterminate state is more of a visual state that just obscures the checked state. If an input is checked and is later made indeterminate, the checked value is still the same. For example:

```
    <body>
      <rux-checkbox checked></rux-checkbox>
      <input checked type="checkbox"/>
      <script>
        const ruxElement = document.querySelector('rux-checkbox')
        const nativeInput = document.querySelector('input')
        setTimeout(() => {
          ruxElement.indeterminate = true
          nativeInput.indeterminate = true

          console.log('Rux Checkbox Checked: ', ruxElement.checked)
          console.log('Native Checkbox Checked: ', nativeInput.checked)
        }, 2000);
      </script>
    </body>
```

Also notice how the native input also doesn't fire any change event. I think it's fine if we want to go against what the native element does if we think there's a better DX, but I see this potentially causing issues if the developer isn't aware that this will trigger a state change and I'm not sure if this offers any improvement. 

What's interesting is that Shoelace appears to be ignoring indeterminate if the checkbox is already selected and Spectrum goes as far as disabling click altogether on indeterminate checkboxes.

2021-08-31 18:06 UTC, Full-lifey commented
> I don't think we actually should be changing the checked value.
> 
> https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type=checkbox)
> https://css-tricks.com/indeterminate-checkboxes/
> 
> Indeterminate state is more of a visual state that just obscures the checked state. If an input is checked and is later made indeterminate, the checked value is still the same. For example:
> 
> ```
>     <body>
>       <rux-checkbox checked></rux-checkbox>
>       <input checked type="checkbox"/>
>       <script>
>         const ruxElement = document.querySelector('rux-checkbox')
>         const nativeInput = document.querySelector('input')
>         setTimeout(() => {
>           ruxElement.indeterminate = true
>           nativeInput.indeterminate = true
> 
>           console.log('Rux Checkbox Checked: ', ruxElement.checked)
>           console.log('Native Checkbox Checked: ', nativeInput.checked)
>         }, 2000);
>       </script>
>     </body>
> ```
> 
> Also notice how the native input also doesn't fire any change event. I think it's fine if we want to go against what the native element does if we think there's a better DX, but I see this potentially causing issues if the developer isn't aware that this will trigger a state change and I'm not sure if this offers any improvement.
> 
> What's interesting is that Shoelace appears to be ignoring indeterminate if the checkbox is already selected and Spectrum goes as far as disabling click altogether on indeterminate checkboxes.

It all depends on where we look for guidance on indeterminate state. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#indeterminate_state_checkboxes):

> Note: If you submit a form with an indeterminate checkbox, the same thing happens as if the checkbox were unchecked — no data is submitted to represent the checkbox.

2021-08-31 18:09 UTC, markacianfrani commented
> > I don't think we actually should be changing the checked value.
> > https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type=checkbox)
> > https://css-tricks.com/indeterminate-checkboxes/
> > Indeterminate state is more of a visual state that just obscures the checked state. If an input is checked and is later made indeterminate, the checked value is still the same. For example:
> > ```
> >     <body>
> >       <rux-checkbox checked></rux-checkbox>
> >       <input checked type="checkbox"/>
> >       <script>
> >         const ruxElement = document.querySelector('rux-checkbox')
> >         const nativeInput = document.querySelector('input')
> >         setTimeout(() => {
> >           ruxElement.indeterminate = true
> >           nativeInput.indeterminate = true
> > 
> >           console.log('Rux Checkbox Checked: ', ruxElement.checked)
> >           console.log('Native Checkbox Checked: ', nativeInput.checked)
> >         }, 2000);
> >       </script>
> >     </body>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also notice how the native input also doesn't fire any change event. I think it's fine if we want to go against what the native element does if we think there's a better DX, but I see this potentially causing issues if the developer isn't aware that this will trigger a state change and I'm not sure if this offers any improvement.
> > What's interesting is that Shoelace appears to be ignoring indeterminate if the checkbox is already selected and Spectrum goes as far as disabling click altogether on indeterminate checkboxes.
> 
> It all depends on where we look for guidance on indeterminate state. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#indeterminate_state_checkboxes):
> 
> > Note: If you submit a form with an indeterminate checkbox, the same thing happens as if the checkbox were unchecked — no data is submitted to represent the checkbox.

Can we just not renderHiddenInput if indeterminate?

2021-08-31 18:20 UTC, Full-lifey commented
> > > I don't think we actually should be changing the checked value.
> > > https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type=checkbox)
> > > https://css-tricks.com/indeterminate-checkboxes/
> > > Indeterminate state is more of a visual state that just obscures the checked state. If an input is checked and is later made indeterminate, the checked value is still the same. For example:
> > > ```
> > >     <body>
> > >       <rux-checkbox checked></rux-checkbox>
> > >       <input checked type="checkbox"/>
> > >       <script>
> > >         const ruxElement = document.querySelector('rux-checkbox')
> > >         const nativeInput = document.querySelector('input')
> > >         setTimeout(() => {
> > >           ruxElement.indeterminate = true
> > >           nativeInput.indeterminate = true
> > > 
> > >           console.log('Rux Checkbox Checked: ', ruxElement.checked)
> > >           console.log('Native Checkbox Checked: ', nativeInput.checked)
> > >         }, 2000);
> > >       </script>
> > >     </body>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also notice how the native input also doesn't fire any change event. I think it's fine if we want to go against what the native element does if we think there's a better DX, but I see this potentially causing issues if the developer isn't aware that this will trigger a state change and I'm not sure if this offers any improvement.
> > > What's interesting is that Shoelace appears to be ignoring indeterminate if the checkbox is already selected and Spectrum goes as far as disabling click altogether on indeterminate checkboxes.
> > 
> > 
> > It all depends on where we look for guidance on indeterminate state. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox#indeterminate_state_checkboxes):
> > > Note: If you submit a form with an indeterminate checkbox, the same thing happens as if the checkbox were unchecked — no data is submitted to represent the checkbox.
> 
> Can we just not renderHiddenInput if indeterminate?

Of course we **can** do that. Is that the functionality we **want**?

2021-09-01 12:10 UTC, markacianfrani commented
> Of course we **can** do that. Is that the functionality we **want**?

What do you think? I think indeterminate states are weird and uncommon enough that it’s better to defer to the native functionality/spec than assume anything ourselves. If it changes the checked state, it could also trigger an unnecessary rerender in its parent.

2021-09-01 17:08 UTC, markacianfrani requested changes
I think ruxChange might be firing too early. If the checkbox is both checked and indeterminate and you click it, the ruxChange event fires, but checked is true when it should be false:

```
<body>
      <rux-checkbox checked indeterminate></rux-checkbox>
      <script>
        const check = document.querySelector('rux-checkbox')
        check.addEventListener('rux-change', (e) => {
          console.log('expect checked to be false: ', e.target.checked);
        })
      </script>
    </body>
```

2021-09-01 17:35 UTC, amalyah commented
The indeterminate state does turn on when you use the Control toggle, but if you click the checkbox when it's in the indeterminate state to change it to the checked or unchecked states in the UI, the Control toggle does not show False as it should.

2021-09-01 17:59 UTC, Full-lifey commented
> The indeterminate state does turn on when you use the Control toggle, but if you click the checkbox when it's in the indeterminate state to change it to the checked or unchecked states in the UI, the Control toggle does not show False as it should.

I believe these controls are one-way data flow from storybook to the component. Currently, there is no data flow from component to storybook (i.e. when clicking the component to change it's state, it does not push the change to the storybook controls.)

I will talk to the dev team about this as it's a global thing

2021-09-01 18:12 UTC, Full-lifey commented
> I think ruxChange might be firing too early. If the checkbox is both checked and indeterminate and you click it, the ruxChange event fires, but checked is true when it should be false:
> 
> ```
> <body>
>       <rux-checkbox checked indeterminate></rux-checkbox>
>       <script>
>         const check = document.querySelector('rux-checkbox')
>         check.addEventListener('rux-change', (e) => {
>           console.log('expect checked to be false: ', e.target.checked);
>         })
>       </script>
>     </body>
> ```

This was due to a previous ticket which stated that an indeterminate checkbox clicked should set checked to true. It has been updated to use the same behavior as a standard checkbox input. This means that clicking it will always flip checked but if indeterminate is true will flip to false.

2021-09-01 18:17 UTC, markacianfrani approved these changes

2021-09-01 18:52 UTC, merged