Astro 1780 select audit
RocketCommunicationsInc/astro-components-stencil pull request #178
Opened 2021-08-30 20:18 UTC by micahjones13

## Brief Description

Audit for rux-select. Added variants, added css to prevent a disabled menu from changing border color on hover, updated the disabled prop description to match our other components, added inputId and labelId args in the stories mdx file to prevent them from showing up as 'undefined'. 

## JIRA Link

https://rocketcom.atlassian.net/browse/ASTRO-1780 --> Audit
https://rocketcom.atlassian.net/browse/ASTRO-1596 --> input id and label id undefined 

## Related Issue

## General Notes

I just put `1` for the label and input ID on the storybook args. This kind of begs the question, maybe these should just be auto-incrementing values? That could be done pretty easily. 

## Motivation and Context

Storybook audit

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.

2021-08-30 20:19 UTC, micahjones13 commented on src/components/rux-select/rux-select.tsx
> +    @Prop({ attribute: 'input-id' }) inputId?: string
I think these could benefit from being auto-incrementing values. @Full-lifey you first built this, what do you think?

2021-08-30 22:35 UTC, nortonprojects requested changes

2021-08-30 22:35 UTC, nortonprojects commented on src/components/rux-select/rux-select.tsx
> +        console.log('input id', this.inputId)
Did you mean to commit this?

2021-08-31 15:05 UTC, micahjones13 commented on src/components/rux-select/rux-select.tsx
> +        console.log('input id', this.inputId)
Sure didn't, thanks!

2021-08-31 20:46 UTC, nortonprojects approved these changes

2021-08-31 21:25 UTC, merged