Astro 1832 angular doc update
RocketCommunicationsInc/astro-components-stencil pull request #226
Opened 2021-09-20 16:34 UTC by Cheshire89

## Brief Description
Update documentation for angular integration

## JIRA Link
https://rocketcom.atlassian.net/browse/ASTRO-1832

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [ ] This PR adds or removes a Storybook story.
-   [ ] I have added tests to cover my changes.

2021-09-20 17:46 UTC, markacianfrani requested changes
Can you copy the markdown format that the other examples are using? https://next--astro-stencil.netlify.app/?path=/story/astro-uxds-welcome-vue-2--page 

missing docs on prop setting

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +Add corresponding theme class (`dark-theme` or `light-theme`) to desire parent container.
dark-theme not needed

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +    <rux-icon slot="left-side" icon="apps" /></rux-icon>
typo. should be `  <rux-icon slot="left-side" icon="apps"></rux-icon>`

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +4. (Optional) In order to set global astro-web-compoennts app styling onto your application.
typo `astro-web-components`

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +Some components offer public methods that can be executed. These methods are async and can be executed by setting a ViewChild decorator on the element.
Can you use an actual component example? ie tree node https://next--astro-stencil.netlify.app/?path=/story/astro-uxds-welcome-javascript--page#methods

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +  <rux-input name="myInput" ngDefaultControl [(ngModel)]="myInputVar"></rux-input>
this doesnt work

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +  @HostListener('rux-change', ['$event.detail'])
we probably dont want to listen for rux-change, as it only gets fired when focus is lost. we want to be listening and binding rux-input.

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +  selector: 'rux-input',
does this work with checkboxes and radios?

2021-09-20 17:46 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +Alternativally ControlValueAccessor directive may be created to omit the use of `ngDefaultControl`.
Where does this file go? Can you provide a full example of a component using this?

2021-09-21 16:35 UTC, Cheshire89 commented on src/stories/welcome/angular.stories.mdx
> +Alternativally ControlValueAccessor directive may be created to omit the use of `ngDefaultControl`.
For someone using angular it self declerative. Any component , directive needs to be declared in a module. in order for it to work

2021-09-21 16:37 UTC, Cheshire89 commented on src/stories/welcome/angular.stories.mdx
> +  @HostListener('rux-change', ['$event.detail'])
Rux change fires whenever value changes (if it's not its a major bug). Not when the focus is lost. Whereas rux-input does not exist on radios, checkboxes and switch. Rux change exists on all form compoents

2021-09-21 16:47 UTC, micahjones13 commented on src/stories/welcome/angular.stories.mdx
> +  @HostListener('rux-change', ['$event.detail'])
That's not the case. https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event
Fires when it's committed, therefore when focus is lost. 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event
Fires whenever value changes

2021-09-22 17:47 UTC, markacianfrani requested changes

2021-09-22 17:47 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +export class RuxInputDirective {
We either need to provide working examples for every form component or just leave this out entirely for now if the schematic is going to include them. External devs are going to have a hard time figuring out which components need these and how our custom events should be mapped properly. We should specify what problem this solves and what the limitations are (afaik angular's form validation won't work without them?)

2021-09-22 17:47 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +<div *ngFor="let button of buttons">
I think this is just a basic angular example, not specific to our components. Segmented button is a better example, as its one of the few components that has a data array property. It might also be worth calling out [attr.foo] for setting attributes that aren't properties. But we don't have any components where that's the case yet.

2021-09-22 17:47 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +4. (Optional) In order to change global astro-web-compoennts styling from default `dark-theme` to `light-theme`.
typo: astro-web-compoennts

actually just omit this section entirely since its not angular specific. we'll add a separate page explaining light-theme and how to activate it

2021-09-22 17:47 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +## Installation
add lazy load and cherry picking instructions

2021-09-22 17:47 UTC, markacianfrani commented on src/stories/welcome/angular.stories.mdx
> +## Integration of astro-web-components into an angular application.
typo: capitalize Angular

2021-09-30 17:48 UTC, markacianfrani approved these changes

2021-09-30 18:08 UTC, merged