fix(rux-radio): prevent change firing twice
RocketCommunicationsInc/astro-components-stencil pull request #239
Opened 2021-09-22 20:27 UTC by markacianfrani

## Brief Description

rux-change was bubbling up from rux-radio and causing rux-radio-group to fire two rux-change events

## JIRA Link

[ASTRO-1851](https://rocketcom.atlassian.net/browse/ASTRO-1851)

## Types of changes

-   [x] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [ ] This PR adds or removes a Storybook story.
-   [ ] I have added tests to cover my changes.

2021-09-22 21:45 UTC, micahjones13 approved these changes

2021-09-22 23:03 UTC, NicDominguez requested changes
Since radio should only be used in radio-group would there be a problem with removing the rux-change event entirely. With setting bubbles to false the event no longer shows in the storybook actions tab which seems odd in comparison to other events.

2021-09-23 13:02 UTC, markacianfrani commented
> Since radio should only be used in radio-group would there be a problem with removing the rux-change event entirely. With setting bubbles to false the event no longer shows in the storybook actions tab which seems odd in comparison to other events.

Yeah let's remove it entirely. This actually bit me working with forms. If you mistakenly add event listeners on the individual radios, it'll appear to work, but cause all sorts of weird issues.

2021-09-23 15:06 UTC, NicDominguez approved these changes

2021-09-23 15:40 UTC, merged