Astro 1829 aos los hide date time labels
RocketCommunicationsInc/astro-components-stencil pull request #250
Opened 2021-09-27 23:36 UTC by Full-lifey

## Brief Description

First, allow for aos and los properties to use either unix time or iso string.
Second, add hideLabels property to hide labels

## JIRA Link

[ASTRO-1829](https://rocketcom.atlassian.net/browse/ASTRO-1829?atlOrigin=eyJpIjoiYWZmYTA3MDMyODdmNDIwZmIyNDQ1YTg1MWUxMDJhYTQiLCJwIjoiaiJ9
[https://rocketcom.atlassian.net/browse/ASTRO-1844](https://rocketcom.atlassian.net/browse/ASTRO-1844?atlOrigin=eyJpIjoiMTRjZWVlYjAyYmY5NGE0Mzk2Y2E3YWI4OWE3NjQ5MTciLCJwIjoiaiJ9)

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

I decided to hide AOS and LOS labels as well. It was only specified to hide the date and time labels. However, I made the judgement call that if a user is going to hide the other labels they will hide those as well. I also thought it looked odd with some labels.

## Types of changes

-   [x] Bug fix
-   [x] New feature
-   [ ] Breaking change

## Checklist

-   [ ] This PR adds or removes a Storybook story.
-   [x] I have added tests to cover my changes.

2021-09-27 23:42 UTC, Full-lifey reviewed
I'm curious about input around storing the AOS/LOS computed value. The big con is it requires more code and is therefore harder to read.

I could just call the method in the render but since we know the clock renders every second this extra computation felt like the bigger con to me.

2021-09-27 23:42 UTC, Full-lifey commented on src/components/rux-clock/rux-clock.tsx
> +    private convertedLos?: string
Added to internal variables so the method wouldn't run on every render (1s).

It doesn't seem computationally heavy to run the method every render but it felt like a waste to me so I chose to do it this way after the first iteration.

2021-09-27 23:42 UTC, Full-lifey commented on src/components/rux-clock/rux-clock.tsx
> +                {!this.hideDate && (
Updated the formatting to simplify the syntax.

2021-09-28 12:31 UTC, markacianfrani approved these changes

2021-09-28 13:51 UTC, amalyah commented
When was small clock added to Storybook? I thought that PR got paused?

2021-09-28 13:55 UTC, markacianfrani commented
> When was small clock added to Storybook? I thought that PR got paused?

That was part of the initial lit port

2021-09-28 13:57 UTC, amalyah commented
Hide labels boolean in the UI is not doing anything in the sample for me.

2021-09-28 15:16 UTC, amalyah commented
> > When was small clock added to Storybook? I thought that PR got paused?
> 
> That was part of the initial lit port

Okay. I wasn't aware that that existed before. Created a ticket for design: https://rocketcom.atlassian.net/browse/ASTRO-2054

2021-09-28 15:18 UTC, amalyah requested changes
Are the booleans for hide labels supposed to work in this PR?

2021-09-28 16:08 UTC, Full-lifey commented
> Are the booleans for hide labels supposed to work in this PR?

Yes they are. It worked on the component but the storybook controls were not hooked up properly. 

This was a great catch and it has been resolved.

2021-09-28 17:57 UTC, merged