Astro 1549 button group bug
RocketCommunicationsInc/astro-components-stencil pull request #59
Opened 2021-07-08 21:23 UTC by Cheshire89

## Brief Description

Update `align` property of button group component to h-align
align is a reserved word and some frameworks my throw an error (Angular did) 

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

## Types of changes

- [ X ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Checklist

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-09 14:22 UTC, markacianfrani requested changes
can you also update button-group.stories.mdx to call the new `args.hAlign` instead of `args.align` ?

2021-07-09 14:22 UTC, markacianfrani commented on src/components/rux-button-group/rux-button-group.tsx
> +    @Prop() hAlign: 'left' | 'center' | 'right' = 'left'
can you add { attribute: 'h-align' } so that the docs render it correctly?

2021-07-09 18:45 UTC, Cheshire89 commented on src/components/rux-button-group/rux-button-group.tsx
> +    @Prop() hAlign: 'left' | 'center' | 'right' = 'left'
lol there is a reason I didnt assign anyone yet :)

2021-07-09 19:58 UTC, markacianfrani requested changes
check the previous comment on button-group.stories.mdx and adding `attribute: h-align` to the prop declaration

2021-07-09 19:58 UTC, markacianfrani commented on src/components/rux-button-group/rux-button-group.tsx
> +    @Prop() hAlign: 'left' | 'center' | 'right' = 'left'
looks like this is still missing

2021-07-09 22:37 UTC, micahjones13 approved these changes

2021-07-12 17:15 UTC, Cheshire89 commented on src/components/rux-button-group/rux-button-group.tsx
> +    @Prop() hAlign: 'left' | 'center' | 'right' = 'left'
There you go ... there was non auto generated properties in the docs which threw me off.

2021-07-13 15:26 UTC, markacianfrani approved these changes

2021-07-13 15:31 UTC, merged