Astro 1556 scroll bar km
RocketCommunicationsInc/astro-components-stencil pull request #62
Opened 2021-07-09 19:18 UTC by micahjones13

## Brief Description

Changed the scroll bar var names and colors to be inline with abstract and KM. 
Dark Theme changes: 

1. Changed `--scrollBarThumbBackgroundColor:` to `rgb(43, 101, 155)` from `rgb(46, 103, 153)`
2. Changed `scrollBarTrackCornerBackgroundColor` to  `--scrollBarTrackBackgroundColor` and changed color to `rgb(27, 45, 62)` from `rgb(32, 50, 70)`
3. Created `scrollBarVerticalBoxShadow` and `scrollBarHorizontalBoxShadow` with values `inset 3px 3px 3px 0px rgba(0, 0, 0, 0.5);` and `inset 1px 3px 3px 0px rgba(0, 0, 0, 0.5)` respectively.

Light Theme changes: 

1. changed `--scrollBarThumbBackgroundColor` to `var(--primary, rgb(0, 90, 143))` from `var(--colorQuaternaryDarken1, #9ba0aa)`
2. Changed `scrollBarTrackCornerBackgroundColor` to  `--scrollBarTrackBackgroundColor` and changed color to `var(--colorWhite, rgb(255, 255, 255));` from `transparent`
3.  Created `scrollBarVerticalBoxShadow` and `scrollBarHorizontalBoxShadow` with values `inset 3px 3px 3px 0px rgba(47, 72, 99, 0.5);` and `inset 1px 3px 3px 0px rgba(47, 72, 99, 0.5)` respectively.

## Related Issue

[Jira Ticket](https://rocketcom.atlassian.net/browse/ASTRO-1556)

## General Notes

I updated the values on the `manager-head.html` to reflect the dark theme version of the scroll bar since the readme sections don't change color when swapping themes, and will soon be switched to docs anyway. 

## Motivation and Context

Updates scroll bar for KM design changes.

## Issues and Limitations

## Types of changes

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-13 13:16 UTC, Full-lifey approved these changes

2021-07-13 13:16 UTC, Full-lifey commented on src/components/rux-switch/rux-switch.scss
> +    width: 30px;
Are these changes intentional because you noticed something?

2021-07-19 20:26 UTC, amalyah requested changes
- I know that _global.scss was updated in the Lit version of the updates. Is that necessary in the Stencil version as well? 
- Where are the sizes of the various scrollbar elements controlled in this version?
- Nice to have: Light theme switch does affect the background color of the Docs tag, so I would still personally recommend allowing the scrollbar theme to change along with the content for theme switches. It's also the only place I can visually check these color settings.

2021-07-19 20:26 UTC, amalyah commented on .storybook/manager-head.html
>          border-radius: 10px;
Thumb's border radius is 4px in design.

2021-07-19 20:26 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --primaryDarker: var(--colorSecondaryDarken2, #2e6799);
Please talk to @NicDominguez regarding best uses of color variables and definitions in this sprint throughout the dark and light theme files. Some of the color definitions for variables don't match Astro UXDS or design files (ex: SecondaryDarken2 is actually #2b659b in design/UXDS) and some variables have had to be used across this sprint's PRs and need to be unified.

2021-07-19 20:26 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --scrollBarThumbBackgroundColor: rgb(43, 101, 155);
Use variable from Nic for this Primary Darker color

2021-07-19 20:26 UTC, amalyah commented on src/global/theme/_theme-dark.scss
>      --scrollBarThumbBackgroundHoverColor: var(
See comment in your Lit PR and question to Daniel there.
https://github.com/RocketCommunicationsInc/astro-components/pull/156#discussion_r670740217

2021-07-19 20:26 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --scrollBarTrackBackgroundColor: rgb(27, 45, 62);
Use variable from Nic for Surface elements

2021-07-19 20:26 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --scrollBarThumbBackgroundColor: var(--primary, rgb(0, 90, 143));
This should be primary color at 70% opacity.

2021-07-19 20:26 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --scrollBarThumbBackgroundHoverColor: var(--colorPrimaryLighten1);
There is no hover state in the designs. See relevant comment in the Lit PR.
https://github.com/RocketCommunicationsInc/astro-components/pull/156#discussion_r670740217

2021-07-21 15:55 UTC, Cheshire89 commented on docs.json
> +          "name": "--switchBackgroundColor",
automated

2021-07-21 22:19 UTC, micahjones13 commented on src/components/rux-button/readme.md
> +| `secondary` | `secondary` | Changes button style from solid to secondary by setting rux-button--secondary class
This would be due to stencil's auto doc generation.

2021-07-21 22:21 UTC, micahjones13 commented on src/global/theme/_theme-light.scss
> +    --scrollBarThumbBackgroundHoverColor: var(--colorPrimaryLighten1);
I took his comment to mean keep it in code - is that correct?

2021-07-21 22:22 UTC, micahjones13 commented on src/global/theme/_theme-light.scss
> +    --scrollBarThumbBackgroundColor: var(--primary, rgb(0, 90, 143));
Should be updated with the latest push.

2021-07-21 22:22 UTC, micahjones13 commented on src/global/theme/_theme-dark.scss
> +    --scrollBarTrackBackgroundColor: rgb(27, 45, 62);
Should be updated with the latest push.

2021-07-21 22:25 UTC, micahjones13 commented
> * I know that _global.scss was updated in the Lit version of the updates. Is that necessary in the Stencil version as well?
> * Where are the sizes of the various scrollbar elements controlled in this version?
> * Nice to have: Light theme switch does affect the background color of the Docs tag, so I would still personally recommend allowing the scrollbar theme to change along with the content for theme switches. It's also the only place I can visually check these color settings.

- The stencil repo is different - the _global.scss in stencil is just a file to meld together all the other global scss files. 
- They are controlled in _reset.scss and the two manager-head.html files in storybook and storybook-next folders.
- The scroll bar should be switching colors now depending on theme.

2021-07-22 13:50 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --scrollBarThumbBackgroundHoverColor: var(--colorPrimaryLighten1);
Yes, I believe you are correct.

2021-07-22 13:52 UTC, amalyah commented on src/global/theme/_theme-dark.scss
>      --scrollBarThumbBackgroundHoverColor: var(
As per Daniel's comment this can stay and design will catch up.

2021-07-22 14:08 UTC, amalyah approved these changes

2021-07-22 14:08 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --scrollBarHorizontalBoxShadow: inset 1px 3px 3px 0px rgba(47, 72, 99, 0.5);
@avillaindesire The scrollbar light theme shadow in the preview is feeling pretty intense. Something to review and see if that's something you want to edit in design files in the future or if I'm missing something in the code that's incorrect.

2021-07-22 14:52 UTC, micahjones13 commented on src/components/rux-tree-node/readme.md
> +Sets the expanded state
These would be from prettier.

2021-07-22 15:48 UTC, micahjones13 commented on src/global/theme/_theme-light.scss
> +    --scrollBarHorizontalBoxShadow: inset 1px 3px 3px 0px rgba(47, 72, 99, 0.5);
@amalyah I'm going to merge this for now - if the shadow ends up being a needed change I can create a separate ticket and get it taken care of.

2021-07-22 15:48 UTC, merged