Astro 1546 remove modal from dom
RocketCommunicationsInc/astro-components-stencil pull request #65
Opened 2021-07-12 19:58 UTC by Cheshire89

## Brief Description

https://rocketcom.atlassian.net/browse/ASTRO-1546

Presently there could be collisions if more than 1 modal is present on the page. Adding and removing modal from dom would fix any of such potential issues .

Add and remove modal from dom.
Simplify implementation.
Hide modal on backdrop click

## JIRA Link

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

## Types of changes

-   [ x ] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [ x ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [ x ] All new and existing tests passed.

2021-07-12 23:47 UTC, markacianfrani requested changes
Can we avoid assigning classes to the Host element here? 

See: [best practices - do not self apply classes](https://developers.google.com/web/fundamentals/web-components/best-practices)

> Elements that need to express their state should do so using attributes. The class attribute is generally considered to be owned by the developer using your element, and writing to it yourself may inadvertently stomp on developer classes.

Also, if we're renaming the component, we still need to keep the original src/story/rux-modal.stories.tsx the same name for regression testing. `src/stories-next/modal.stories.mdx` is where you'll want to make this change. 

--

2021-07-13 15:38 UTC, Full-lifey commented on src/components/rux-modal/rux-modal.tsx
> +        return open ? (
Can use `open && ()` and remove 165

2021-07-13 15:42 UTC, Full-lifey reviewed
I have to agree with Mark on the open class. 

Once that is done I will approve

2021-07-15 16:29 UTC, markacianfrani commented on src/components/rux-modal/rux-modal.scss
> +:host(.open) {
can remove

2021-07-15 16:29 UTC, markacianfrani commented on src/components/rux-modal/rux-modal.tsx
> +        setTimeout(() => {
Do we really want this to trigger after every render?

Also, I tried updating the modal title/message props after the initial render but they don't appear to change.

2021-07-15 16:29 UTC, markacianfrani commented on src/components/rux-modal/rux-modal.tsx
> +                button.setAttribute('tabindex', '0')
Can you explain what's going on here? Why does the denyText button have tabindex=-1 but the confirmText is 0?

2021-07-15 16:31 UTC, markacianfrani commented
make sure to you're merging this into next (currently set to main)

2021-07-16 00:57 UTC, markacianfrani requested changes

2021-07-16 00:57 UTC, markacianfrani commented on src/components/rux-modal/rux-modal.tsx
>      componentDidRender() {
Using componentDidRender will cause the button to be focused after every render. Which could cause issues if the developer changes any props like the message or title. 

An exaggerated example of this can actually be seen right in the storybook story: https://deploy-preview-65--astro-stencil.netlify.app/?path=/story/components-modal--modal&args=confirmText:Release . 

Open the controls pane. and edit any of the strings like confirm-text. As soon as you type a letter, the focus leaves the input and focuses the button. 

I think the expected behavior should be to only focus after the open event.

2021-07-16 15:41 UTC, Cheshire89 commented on src/components/rux-modal/rux-modal.tsx
>      componentDidRender() {
Since there is only one property that is reflected (open) this should not be an issue

2021-07-16 15:45 UTC, Cheshire89 commented on src/components/rux-modal/rux-modal.tsx
> +                button.setAttribute('tabindex', '0')
The tabindex global attribute indicates that its element can be focused, and where it participates in sequential keyboard navigation (usually with the Tab key, hence the name).

.ie it sets denyText to = -1  and confirm Text to 0  which prioritizes confirm button in the focus chain

2021-07-19 13:15 UTC, markacianfrani commented
failing to build, looks like the h-align changes need to be merged in?

2021-07-20 22:18 UTC, Cheshire89 reviewed
> failing to build, looks like the h-align changes need to be merged in?

I'm not sure how it didnt jump out when I pushed back then. All is fixed now

2021-07-21 13:28 UTC, markacianfrani requested changes
the Release button is no longer receiving focus immediately. It seems to work if you toggle open, but not on the initial render.

2021-07-21 15:59 UTC, markacianfrani requested changes
I think you may have missed my last comment:

the Release button is no longer receiving focus immediately. It seems to work if you toggle open, but not on the initial render.

2021-07-21 16:07 UTC, markacianfrani approved these changes

2021-07-21 19:36 UTC, Full-lifey approved these changes

2021-07-22 16:05 UTC, merged