Astro 1439 input
RocketCommunicationsInc/astro-components-stencil pull request #67
Opened 2021-07-16 13:34 UTC by markacianfrani

## Brief Description

Creates a rux-input-field component

## JIRA Link

[ASTRO-1439](https://rocketcom.atlassian.net/browse/ASTRO-1439)

## General Notes

If you can find the TRON reference in this PR, I'll buy you lunch.

## Issues and Limitations

* Built in form validation currently does not work due to an oversight in how we were planning to handle the shadow dom limitation with hidden inputs. Will be investigating [stencil-forms](https://github.com/adamdbradley/stencil-forms) for some better ideas on how to handle that. 
* All regressions pass except for the textarea sections because that's not built yet

## Types of changes

-   [x] New feature

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

2021-07-16 16:49 UTC, NicDominguez requested changes
So organized and readable. Most impressive! Just a couple of controls that are not synced up to fix.

2021-07-16 16:49 UTC, NicDominguez commented on src/stories-next/input.stories.mdx
> +        .value="${args.value}"
I am still getting use to the mdx format but I believe you are missing the type and step props here as they are not working in storybook.

Type is also missing in the other stories.

2021-07-16 16:49 UTC, NicDominguez commented on src/components/rux-input-field/rux-input-field.tsx
> +    inputElement?: HTMLInputElement
Do you need the @Element decorator here?

2021-07-19 13:36 UTC, markacianfrani commented on src/stories-next/input.stories.mdx
> +        .value="${args.value}"
good catch!

2021-07-19 13:37 UTC, markacianfrani commented on src/components/rux-input-field/rux-input-field.tsx
> +    inputElement?: HTMLInputElement
removed the ref entirely in favor of events.

2021-07-19 20:41 UTC, amalyah commented
Note from PR review meeting from Duncan: The request for my review is not necessary here.

2021-07-21 16:03 UTC, Cheshire89 reviewed
Is there a reason your input stories differ from the format we had in astro-components ?

2021-07-21 16:10 UTC, markacianfrani commented
> Is there a reason your input stories differ from the format we had in astro-components ?

The new MDX stories follow the convention laid out in https://rocketcom.atlassian.net/wiki/spaces/AS11/pages/1999568934/MDX+Format+Template which was largely taken from Storybook's best practices. The idea is to isolate each variant as their own separate story.

The old layout had a lot of unnecessary states like invalid number + invalid text. They're basically the same thing.

2021-07-21 19:18 UTC, NicDominguez approved these changes

2021-07-21 20:46 UTC, micahjones13 commented on src/stories/rux-form-elements.stories.tsx
> +      <input class="rux-input-field" type="date" id="input__date" value="1970-01-01">
Tron release date?

2021-07-21 20:47 UTC, micahjones13 approved these changes

2021-07-21 20:54 UTC, micahjones13 commented on src/stories/rux-form-elements.stories.tsx
> +      <input class="rux-input-field" type="date" id="input__date" value="1970-01-01">
That can't be right but it's gotta have something to do with this date lol

2021-07-22 13:33 UTC, merged