Astro 1582 popup story
RocketCommunicationsInc/astro-components-stencil pull request #69
Opened 2021-07-20 13:45 UTC by markacianfrani

## Brief Description

Added missing MDX story for popup menu

## JIRA Link

[ASTRO-1582](https://rocketcom.atlassian.net/browse/ASTRO-1582)

## Motivation and Context

Looks like it was missing.

## Issues and Limitations

There are some issues at the component level with iframes. See https://rocketcom.atlassian.net/browse/ASTRO-1566

## Types of changes

-   [x] New feature

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

2021-07-21 16:06 UTC, Cheshire89 reviewed
In default story when clicked into main field popup disappears. Is there a way to override that behavior for the default story only ?

2021-07-21 16:15 UTC, markacianfrani commented
Not sure we'd want to since that's the intended behavior. Might be a smell that we should expose a "clickToClose" Boolean prop. @Full-lifey thoughts?

2021-07-22 15:13 UTC, Full-lifey requested changes
I don't understand the use-case of the first story. 

Also, both stories are showing two unnamed JSON String props on the right.

2021-07-22 15:13 UTC, Full-lifey commented on src/stories-next/popup.stories.mdx
> +}
Do we want to have the menu show without a trigger element? I don't see that being a use-case

2021-07-22 15:30 UTC, markacianfrani commented on src/stories-next/popup.stories.mdx
> +}
https://deploy-preview-69--astro-stencil.netlify.app/?path=/story/components-pop-up-menu--default-story is showing them named for me? 

The default story should only show the component in isolation. The trigger/anchor elements aren't part of the component. The variant story is there to show how it would work with a plain button.

2021-07-22 15:41 UTC, micahjones13 requested changes
When on the default story, if you switch to docs and then back to the default the popup moves downward. Right clicking anywhere will close the popup (as expected I think), but when toggling the open control after that the popup moves downward again. 
Light theme doesn't show any text. Doesn't work on anchor either so I'm assuming that it never got implemented correctly

2021-07-22 16:04 UTC, markacianfrani commented
> When on the default story, if you switch to docs and then back to the default the popup moves downward. Right clicking anywhere will close the popup (as expected I think), but when toggling the open control after that the popup moves downward again.
> Light theme doesn't show any text. Doesn't work on anchor either so I'm assuming that it never got implemented correctly

Good catch. There's some outstanding bugs with the component itself. I added those steps to that ticket https://rocketcom.atlassian.net/browse/ASTRO-1566 

This PR was mainly just to get the initial story back into the repo because it was missing for some reason.

2021-07-22 16:09 UTC, micahjones13 approved these changes

2021-07-22 16:39 UTC, Full-lifey commented on src/stories-next/popup.stories.mdx
> +}
I do see those properties on the deployment, it must have been something on my end.

I understand trying to show only the component in theory but in practice this doesn't make sense to me. Isn't the point of storybook to document usage and show examples? If I put myself in our users' shoes I will need to go to the second story in order to use the component and see how it works anyway. As a user, since I can see an example in the second story what purpose does the first story have to me?

2021-07-22 21:28 UTC, markacianfrani commented
@Full-lifey added rux icon as a trigger element here. it's currently bugged but should be resolved in one of those upcoming fixes

2021-07-22 22:52 UTC, nortonprojects approved these changes

2021-07-22 22:52 UTC, nortonprojects commented on src/stories-next/popup.stories.mdx
> +import RuxPopUpMenu from '@astrouxds/astro-web-components/dist/components/rux-pop-up-menu.js'
Kind of a nitpick, but if we make sure our components are marked as side-effect free we can get rid of the big nested import and just have it be like this:

```
import RuxPopUpMenu from '@astrouxds/astro-web-components`
```

2021-07-26 17:30 UTC, Full-lifey approved these changes

2021-07-26 18:09 UTC, merged