Astro 1443 create stencil select
RocketCommunicationsInc/astro-components-stencil pull request #70
Opened 2021-07-20 16:19 UTC by Full-lifey

## Brief Description

Create Stencil component for the Select Menu. This change also implements the Kobiashi Maru style updates.

This component renders native elements and utilizes a slot for select menu options.

## JIRA Link

[ASTRO-1443](https://rocketcom.atlassian.net/secure/RapidBoard.jspa?rapidView=77&projectKey=ASTRO&modal=detail&selectedIssue=ASTRO-1443)
[ASTRO-1529](https://rocketcom.atlassian.net/secure/RapidBoard.jspa?rapidView=77&projectKey=ASTRO&modal=detail&selectedIssue=ASTRO-1529)

## Related Issue

## General Notes
This component has Shadow DOM off and uses Scopes Styles instead. Shadow DOM prevents the menu from appearing at all.

## Motivation and Context

It creates a Select Stencil component. It renders native elements

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2021-07-21 16:31 UTC, Full-lifey commented on src/global/theme/_theme-dark.scss
> +    );
Had to add a linear-gradient for the background color behind the caret. The colors themselves could not be CSS custom properties or the function would not work.

Add it to the reasons for SCSS variable usage.

2021-07-21 19:57 UTC, amalyah requested changes

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +      * --selectMenuTextHoverColor: Text Hover Color of the Select Menu
Is this of the Select Input or the menu options?

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +      * --selectMenuBorderDisabledColor: Border Color of the Disabled Select Input
As a note, we are only using opacity for disabled. No color changes.

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +      * @prop --selectMenuHoverOptBackgroundColor: Background Hover Color of Select Menu Options
Nice to Have: change to --selectMenuOptHoverBackgroundColor for naming consistency

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +      * @prop --selectOptGroupTextColor: Text Color of Select Menu Option Group
Nice to Have: --selectMenuOptGroupTextColor (for naming consistency)

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +      * @prop --selectInactiveCaret: Caret Shown When the Select Menu is Closed
Nice to Have: --selectMenuInactiveCaret (for naming consistency)

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +      * @prop --selectMenuHoverOptBackgroundColor: Background Hover Color of Select Menu Options
Is there a reason that some get the @prop text and others in these comments don't?

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +      * @prop --selectActiveCaret: Caret Shown When the Select Menu is Open
Nice to Have: --selectMenuActiveCaret (for naming consistency)

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +label {
Are the properties below different for other components? On the design side, labels always have the same styling (though I admit that they may be above a field or to the left of one).

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +        border-color: var(--selectMenuBorderDisabledColor);
This is not in use though I understand if you want to keep it to future-proof.

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +        // &:hover {
Should this comment be removed now that the not-allowed cursor is in the disabled declaration?

2021-07-21 19:57 UTC, amalyah commented on src/components/rux-select/rux-select.scss
> +            color: var(--selectMenuTextHoverColor);
I'm guessing that this is supposed to be --selectMenuOptTextHoverColor instead since the two variables are supposed to have two different color definitions.

2021-07-21 19:57 UTC, amalyah commented on src/global/_variables.scss
> -    Drop Down/Select Colors
Is this removal because it all got moved to the dark and light theme files?

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBorderColor: rgb(43, 101, 155);
Please talk to @NicDominguez regarding appropriate variables to use for the Primary Darker color.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBorderHoverColor: rgb(146, 203, 255);
Could you use a variable here instead? Like --primaryLight

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBorderFocusColor: var(--primary);
Please change to the Primary Light variable instead.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBorderDisabledColor: #2b659b;
We no longer have any specific coloring for disabled states. It's just 40% opacity for the whole thing.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +        #1c3f5e 2rem,
Please talk to @NicDominguez regarding appropriate variables to use for the Dark Selected color here if variables are allowed in this gradient declaration.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +        #101923 2rem
Since we don't actually use a gradient in the design, could you make the second value the same as the first value?

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuTextHoverColor: rgb(146, 203, 255);
If this is for the Select Input text on hover, then this should be --primary. If this is for the Select Menu option text on hover, then this should use the Primary Light variable.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuLabelColor: #ffffff;
Nice to Have: Default Text variable

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --selectMenuBorderColor: rgb(100, 156, 189);
Please talk to @NicDominguez to use the correct variable for the Primary Lighter color.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --selectMenuBorderHoverColor: rgb(0, 72, 114);
Please use the Primary Dark variable here.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --selectMenuBorderDisabledColor: #649cbd;
Not in use. Only opacity changed for disabled components.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --selectMenuInvalidBorderColor: #ff3838;
--criticalBorder

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +        #cee9fc 2rem,
If you can, please use the Light Selected color variable here. Ask Nic if that's not already merged in.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +        #eaeef4 2rem
Please change this to be the same as the first value.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --selectMenuTextHoverColor: rgb(0, 72, 114);
--primary if this is Select Input text hover. --primaryDark if this is Select Menu Option text hover.

2021-07-21 19:57 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --selectMenuLabelColor: #292a2d;
Would suggest --defaultText here since all of our labels are supposed to be the same.

2021-07-21 21:04 UTC, Full-lifey commented on src/components/rux-select/rux-select.scss
> +        // &:hover {
Done.

2021-07-21 21:43 UTC, micahjones13 requested changes
No caret or background color on light theme, but it shows up briefly if you toggle any of the states (ie. disabled, ect).

2021-07-21 21:43 UTC, micahjones13 commented on src/global/theme/_theme-light.scss
> +    --selectMenuBackgroundColor: linear-gradient(
Caret isn't showing up in light theme on storybook - says the `--selectMenuInactiveCaret` isn't defined in the background image - but it goes right back to being defined when swapped back to dark theme. 🤷

2021-07-21 21:43 UTC, micahjones13 commented on src/global/theme/_theme-light.scss
> +    --selectMenuBackgroundColor: linear-gradient(
When toggling disabled state, you can see it show up for a brief moment.

2021-07-21 21:49 UTC, Full-lifey commented on src/global/theme/_theme-light.scss
> +    --selectMenuBackgroundColor: linear-gradient(
It was a typo when updating the CSS custom property name within rux-select.scss

It has been resolved.

2021-07-21 21:49 UTC, micahjones13 commented on src/global/theme/_theme-dark.scss
> +        #1c3f5e 2rem,
They are, I used 2 css vars in a linear-gradient on the astro-components select. However, this is a different use case and the linear-gradient is structured different, so that may be the issue with the custom vars. Joel and I talked about this already and we'll continue investigating. Just an FYI for you @amalyah

2021-07-21 23:56 UTC, NicDominguez approved these changes
The component looks great. I'll talk with @amalyah and @dmcalester about getting the new color variables in and other global style changes that need to take place. Nicely done with this port.

2021-07-21 23:56 UTC, NicDominguez commented on src/components/rux-select/rux-select.tsx
> +    @Element() el!: HTMLRuxSelectElement
I am probably just missing something but why do we have the Element decorator here if it is not referenced anywhere else?

2021-07-22 14:12 UTC, markacianfrani requested changes
- Form Submission
I'm not able to submit the select value using a native form. I would expect to be able to since its not shadow dom. I think you just need to expose a name property.
```
        <form method="POST">
          <!-- works-->
            <select name="vanilla">
                <option value="" selected>Select an Option</option>
                <optgroup label="Group one">
                    <option>Option 1.1</option>
                    <option>Option 1.2</option>
                    <option>Option 1.3</option>
                    <option>Option 1.4</option>
                </optgroup>
                <optgroup label="Group two">
                    <option>Option 2.1</option>
                    <option>Option 2.2</option>
                    <option>Option 2.3</option>
                    <option>Option 2.4</option>
                </optgroup>
            </select>

            <!-- doesnt-->
            <rux-select
                name="astro"
                label-id="whatup"
                input-id="name"
                label="helloworld"
            >
                <option value="" selected>Select an Option</option>
                <optgroup label="Group one">
                    <option>Option 1.1</option>
                    <option>Option 1.2</option>
                    <option>Option 1.3</option>
                    <option>Option 1.4</option>
                </optgroup>
                <optgroup label="Group two">
                    <option>Option 2.1</option>
                    <option>Option 2.2</option>
                    <option>Option 2.3</option>
                    <option>Option 2.4</option>
                </optgroup>
            </rux-select>
            <button type="submit">submit</button>
        </form>
```

- Above example is rendering a blank white box. Old storybook story seems to work though so maybe it's something on my end.

- I think this should still expose a value property and emit change events. Even though its not shadow dom encapsulated, you should still be able to interact with the components public API.

2021-07-22 14:12 UTC, markacianfrani commented on src/components/rux-select/rux-select.tsx
> +    @Prop({ attribute: 'label-id' }) labelId?: string
Why would we need or want to pass in a label id? I think aria-labelledby makes sense if label were a slot, but why not just use label for="inputid" ?

2021-07-22 16:02 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +        #101923 2rem
Yes, but I believe you can set both ends of the gradient to the same color? @micahjones13 how did you handle that in your gradient in astro-components? Can the same approach work here?

2021-07-22 16:03 UTC, Cheshire89 commented on src/global/theme/_theme-light.scss
> +        #cee9fc 2rem,
assign Light Selected to scss var and use that instead ? will make future tweaks easier.

2021-07-22 16:04 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +    --selectMenuInvalidBorderColor: #ff3838;
Light library keeps tripping me up with the critical color. You are correct that it should stay the bright red color. Bonus points if there's a variable you can use for that.

2021-07-22 16:10 UTC, amalyah requested changes

2021-07-22 16:10 UTC, amalyah commented on src/components/rux-select/readme.md
> +    <option value="" selected>Select an Option</option>
Change label and value to use sentence case in lines 30-31

2021-07-22 16:10 UTC, amalyah commented on src/global/theme/_theme-light.scss
> +        #eaeef4 2rem
Does it throw an error when the hex value of the start and end points are the same in the gradient?

2021-07-22 16:10 UTC, amalyah commented on src/stories-next/select.stories.mdx
> +                <option value="" selected>Select an Option</option>
Select an option

2021-07-22 16:10 UTC, amalyah commented on src/stories/rux-select.stories.tsx
> +                <rux-select label="Select an Option">
Select an option

2021-07-22 16:10 UTC, amalyah commented on src/stories/rux-select.stories.tsx
> +                    <option value="" selected>Select an Option</option>
Select an option

2021-07-22 16:11 UTC, Full-lifey commented on src/components/rux-select/rux-select.tsx
> +    @Prop({ attribute: 'label-id' }) labelId?: string
I tried and I get a TS error.

> Type '{ id: string | undefined; for: string; }' is not assignable to type 'LabelHTMLAttributes<HTMLLabelElement>'.
  Property 'for' does not exist on type 'LabelHTMLAttributes<HTMLLabelElement>'. Did you mean 'htmlFor'?ts(2322)

2021-07-22 16:13 UTC, Full-lifey commented on src/components/rux-select/rux-select.tsx
> +    @Element() el!: HTMLRuxSelectElement
I was planning on using it for id fetching from the rux-select but ended up going with a property instead. I will remove

2021-07-22 19:16 UTC, Full-lifey commented on src/components/rux-select/rux-select.tsx
> +    @Prop({ attribute: 'label-id' }) labelId?: string
Looks like it's a JSX issue. htmlFor appears to be the usage in this format.

2021-07-23 00:08 UTC, nortonprojects commented
![image](https://user-images.githubusercontent.com/9831043/126723714-da972504-8ff3-4a67-b929-ff24170cc61d.png)

The Mac version looks fine, but on Linux it looks a bit off color-wise. I'd assume the Windows version looks similar without the Mac styling

2021-07-23 15:40 UTC, micahjones13 commented on src/components/rux-select/rux-select.scss
> +    option {
option should have a :focus selector as well: ```option:focus {
    color: var(--selectMenuOptSelectedTextColor);
    background-color: var(--selectMenuOptSelectedBackgroundColor);
}```
This was one of the last updates I made to the astro-components repo before merge.

2021-07-26 15:37 UTC, Full-lifey commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBorderColor: rgb(43, 101, 155);
I found it previously added and replaced with the --surfaceElements variable.

2021-07-26 15:39 UTC, Full-lifey commented on src/global/theme/_theme-dark.scss
> +        #1c3f5e 2rem,
I did some further testing and got it working with CSS Custom Properties.

I still want to update everything to SCSS variables at some point as they have more features and compile down to directly coded values anyway.

2021-07-26 15:43 UTC, Full-lifey commented on src/global/theme/_theme-dark.scss
> +        #101923 2rem
Micah took a different approach and the one he took had issues with re-sizing the input. There was a hard-coded width for the background color and when resizing the caret background color would expand instead of the other color. 

Using linear-gradient to provide the two background colors was the best way I could find to set the caret background width fixed so that the input background color would resize instead of the other way around.

2021-07-26 15:45 UTC, Full-lifey commented on src/global/theme/_theme-light.scss
> +    --selectMenuBorderColor: rgb(100, 156, 189);
Found it after a merge of next and have updated accordingly

2021-07-26 15:45 UTC, Full-lifey commented on src/global/theme/_theme-light.scss
> +        #cee9fc 2rem,
Done

2021-07-26 15:46 UTC, Full-lifey commented on src/global/theme/_theme-light.scss
> +        #eaeef4 2rem
Resolved after testing

2021-07-26 16:18 UTC, Full-lifey commented on src/components/rux-select/rux-select.scss
> +    option {
Added

> ![image](https://user-images.githubusercontent.com/9831043/126723714-da972504-8ff3-4a67-b929-ff24170cc61d.png)
> 
> The Mac version looks fine, but on Linux it looks a bit off color-wise. I'd assume the Windows version looks similar without the Mac styling

Different OS's and different browsers display/allow different styling on native select menus. Unfortunately I don't think much can be done. Besides, the long-term plan is to replace the native elements with components so we can have further functionality.

2021-07-27 15:16 UTC, Full-lifey commented
> * Form Submission
>   I'm not able to submit the select value using a native form. I would expect to be able to since its not shadow dom. I think you just need to expose a name property.
> 
> ```
>         <form method="POST">
>           <!-- works-->
>             <select name="vanilla">
>                 <option value="" selected>Select an Option</option>
>                 <optgroup label="Group one">
>                     <option>Option 1.1</option>
>                     <option>Option 1.2</option>
>                     <option>Option 1.3</option>
>                     <option>Option 1.4</option>
>                 </optgroup>
>                 <optgroup label="Group two">
>                     <option>Option 2.1</option>
>                     <option>Option 2.2</option>
>                     <option>Option 2.3</option>
>                     <option>Option 2.4</option>
>                 </optgroup>
>             </select>
> 
>             <!-- doesnt-->
>             <rux-select
>                 name="astro"
>                 label-id="whatup"
>                 input-id="name"
>                 label="helloworld"
>             >
>                 <option value="" selected>Select an Option</option>
>                 <optgroup label="Group one">
>                     <option>Option 1.1</option>
>                     <option>Option 1.2</option>
>                     <option>Option 1.3</option>
>                     <option>Option 1.4</option>
>                 </optgroup>
>                 <optgroup label="Group two">
>                     <option>Option 2.1</option>
>                     <option>Option 2.2</option>
>                     <option>Option 2.3</option>
>                     <option>Option 2.4</option>
>                 </optgroup>
>             </rux-select>
>             <button type="submit">submit</button>
>         </form>
> ```
> 
> * Above example is rendering a blank white box. Old storybook story seems to work though so maybe it's something on my end.
> * I think this should still expose a value property and emit change events. Even though its not shadow dom encapsulated, you should still be able to interact with the components public API.

I added the name property and the event emitter. Because it's using a native select element the value prop was not added.

2021-07-27 15:24 UTC, amalyah requested changes

2021-07-27 15:24 UTC, amalyah commented on src/components/rux-select/readme.md
> +    label="Select an Option"
Select an option

2021-07-27 15:24 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBorderColor: var(--surfaceElements);
Change to --primaryDarker or whatever the latest variable for #2b659b / 43,101,155 is.

2021-07-27 15:24 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBackgroundColor: linear-gradient(
Is there a ticket to investigate a better solution around this background color bug in the backlog?

2021-07-27 15:30 UTC, micahjones13 commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBackgroundColor: linear-gradient(
Because this component uses the native HTML select element, this may be the best solution to having two different colors as backgrounds. I think if we wanted to improve it, we would need to rewrite this component without using the native select.

2021-07-27 15:46 UTC, markacianfrani requested changes
Can we get this to pass regressions? You'll just need to change the title in `rux-select.stories.tsx` back to `title: 'Components/Form Elements',` so backstop can pick it up and rename 'Select an option' to 'Enabled' to reflect what's currently on the lit repo. 

Looks like very minor changes--different borders, error text size. 

Or if the lit repo @ next is currently wrong, we can make a ticket for that.

2021-07-27 15:49 UTC, Full-lifey commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBackgroundColor: linear-gradient(
Correct. However, the resize background bug still exists in astro-components and we DO need a ticket for that.

2021-07-27 15:50 UTC, micahjones13 commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBackgroundColor: linear-gradient(
Good call, I'll make one right now.

2021-07-27 16:17 UTC, amalyah commented on src/global/theme/_theme-dark.scss
> +    --selectMenuBackgroundColor: linear-gradient(
Ah I understand now. Resolved for my concern.

2021-07-27 16:24 UTC, amalyah approved these changes

2021-07-27 18:00 UTC, Full-lifey commented
> Can we get this to pass regressions? You'll just need to change the title in `rux-select.stories.tsx` back to `title: 'Components/Form Elements',` so backstop can pick it up and rename 'Select an option' to 'Enabled' to reflect what's currently on the lit repo.
> 
> Looks like very minor changes--different borders, error text size.
> 
> Or if the lit repo @ next is currently wrong, we can make a ticket for that.

I have resolved all of the minor changes needed to match the stories. However, We won't be able to get it to pass regressions due to a background color bug making the caret background the incorrect size on the lit repo.

2021-07-27 19:46 UTC, nortonprojects approved these changes

2021-07-27 20:16 UTC, micahjones13 approved these changes

2021-07-28 00:07 UTC, markacianfrani requested changes
>  However, We won't be able to get it to pass regressions due to a background color bug making the caret background the incorrect size on the lit repo.

What bug is that? Is there a ticket? 

Looks like dark theme regressions are passing for me? But theres still a sizing issue with the caret box on the light theme though that should be addressed

2021-07-28 00:07 UTC, markacianfrani commented on src/components/rux-select/readme.md
> +| `--fontFamily`                           | Font Family for the Application               |
fontFamily is application wide and not component specific

2021-07-28 00:30 UTC, markacianfrani requested changes
>  However, We won't be able to get it to pass regressions due to a background color bug making the caret background the incorrect size on the lit repo.

What bug is that? Is there a ticket? 

Looks like dark theme regressions are passing for me. 
1. Theres still a sizing issue with the caret box on the light theme though.
2. I'm still not getting any styling just using plain HTML/CSS inside index.html
```
      <rux-select label="Select an Option">
            <option>
              Option 1.1
            </option>
            <option>
              Option 1.2
            </option>
            <option>
              Option 1.3
            </option>
            <option>
              Option 1.4
            </option>
       </rux-select>
```

2021-07-28 00:30 UTC, markacianfrani commented on src/components/rux-select/rux-select.tsx
> +    inputId?: string = `rux-select-${selectIds++}`
This is showing up as a string 'rux-select-${selectIds++}' in the API docs. 

Created ticket ASTRO-1597

2021-07-28 00:30 UTC, markacianfrani commented on src/stories-next/select.stories.mdx
> +                input-id="${args.inputId}"
These are rendering the input-id and label-id as undefined by default. Made a new ticket ASTRO-1596

2021-07-28 00:30 UTC, markacianfrani commented on src/components/rux-select/rux-select.tsx
> +    @Event({ eventName: 'rux-select-changed' })
event name should be 'rux-change' to be consistent with other components

2021-07-28 14:22 UTC, markacianfrani approved these changes

2021-07-28 15:54 UTC, Full-lifey commented
> > However, We won't be able to get it to pass regressions due to a background color bug making the caret background the incorrect size on the lit repo.
> 
> What bug is that? Is there a ticket?
> 
> Looks like dark theme regressions are passing for me.
> 
> 1. Theres still a sizing issue with the caret box on the light theme though.
> 2. I'm still not getting any styling just using plain HTML/CSS inside index.html
> 
> ```
>       <rux-select label="Select an Option">
>             <option>
>               Option 1.1
>             </option>
>             <option>
>               Option 1.2
>             </option>
>             <option>
>               Option 1.3
>             </option>
>             <option>
>               Option 1.4
>             </option>
>        </rux-select>
> ```

It's a bug where the background of the caret section expands or contracts based on the width of the component. This was resolved with this component. This is documented in ASTRO-1594 by Micah.

2. We talked about this but there is an application-wide issue with dark-theme variables not populating without the dark-theme class being applied.

2021-07-28 18:20 UTC, merged