Astro 1571 checkbox
RocketCommunicationsInc/astro-components-stencil pull request #72
Opened 2021-07-21 18:35 UTC by Cheshire89

## Brief Description

Added checkbox component
In addition to jest tests also tested the component in Angular to make sure ngModel biding works

## JIRA Link

https://rocketcom.atlassian.net/browse/ASTRO-1571

## Related Issue

## General Notes

## Motivation and Context

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the documentation.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

2021-07-22 15:54 UTC, Full-lifey requested changes
Please also update the merge into branch to next.

2021-07-22 15:54 UTC, Full-lifey commented on src/components/rux-checkbox/rux-checkbox.tsx
> +     */
Please update descriptions of props.

2021-07-22 15:54 UTC, Full-lifey commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop({ reflect: true, mutable: true }) value: boolean | null = null
Please explain the use-case of this prop as a boolean. When looking at the lifecycle methods it appears to be tied directly to the checked prop so why not just use checked?

2021-07-22 16:01 UTC, Cheshire89 commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop({ reflect: true, mutable: true }) value: boolean | null = null
@NicDominguez  because angular ties into value property to make ngModel accessible. After convo with Mark however it will get updated to not set boolean type definition as it overrides native html behavior of a value on a checkbox.

Instead we'll add Stencil Angular wrapper which will hopefully fix any binding issues

2021-07-22 22:01 UTC, markacianfrani requested changes
* Error Text doesn't do anything
* Missing MDX story
* Indeterminate not functioning correctly. See native example:
If indeterminate, clicking sets checked true.
```
    <rux-checkbox error-text="hello" indeterminate></rux-checkbox>
      <input type="checkbox" indeterminate/>
      <script>
        const input = document.querySelector('input');
        input.indeterminate = true
      </script>
```

2021-07-27 17:59 UTC, markacianfrani requested changes
Indeterminate not functioning correctly. See native example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate
If indeterminate, clicking sets checked true.


```
    <rux-checkbox error-text="hello" indeterminate></rux-checkbox>
      <input type="checkbox" indeterminate/>
      <script>
        const input = document.querySelector('input');
        input.indeterminate = true
      </script>
      ```

2021-07-27 18:36 UTC, markacianfrani commented on src/components/rux-checkbox/rux-checkbox.scss
> +        display: none;
we shouldn't actually need this or any of the hacky psuedo elements anymore with [appearance](https://caniuse.com/css-appearance). just an aside for a future refactor

2021-07-27 18:52 UTC, markacianfrani commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop({ reflect: true, mutable: true }) value: string = ''
does this still need to be mutable?

2021-07-28 14:29 UTC, Cheshire89 commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop({ reflect: true, mutable: true }) value: string = ''
I will keep it for now. Since I will need it or angular integration later

2021-07-28 14:33 UTC, Cheshire89 commented
> Indeterminate not functioning correctly. See native example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate
> If indeterminate, clicking sets checked true.
> 
> ```
>     <rux-checkbox error-text="hello" indeterminate></rux-checkbox>
>       <input type="checkbox" indeterminate/>
>       <script>
>         const input = document.querySelector('input');
>         input.indeterminate = true
>       </script>
>       ```
> ```
never knew its actually an attribute

2021-07-28 15:45 UTC, markacianfrani commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop({ reflect: true, mutable: true }) value: string = ''
Why's that? If you update the value of a prop internally, the parent won't know about it. React will even reset it to whatever it thinks it should be on each render. Mutable props violate the whole idea of props down, events up.

2021-07-28 16:04 UTC, markacianfrani requested changes
Regression tests failing. We don't need to show any of the error or help text in the .tsx story. It just needs what's in the current lit repo. Looks like there's some decent regressions in color, sizing.

2021-07-28 16:16 UTC, micahjones13 requested changes
It seems that you have to click the box twice for it to register as checked the first time you want to check it: I am running just 
```
 <rux-checkbox
         name="checkboxGroup"
          id="checkbox4c"
          indeterminate
           checked
            >
                Label Text
 </rux-checkbox>
```
and when clicking the box the first time, nothing happens. Do it again and it checks the box, and then works as expected. It looks like having checked passed in the above example is what causes the first click to not register. 
When passing in `checked="true"`, I'd think the box would be checked already? It seems like the component thinks it's checked already, but you can't tell visually (no check mark in box), and thus you have to click it twice to see the check mark appear. This is the case with just passing in `checked` as well. 

It doesn't seem that having `indeterminate` passed in changes the check to a line inside the box. 

Is there a desire at all to have help and error text be able to be present at the same time? I think that would be useful to a user.

2021-07-28 16:16 UTC, micahjones13 commented on src/components/rux-checkbox/rux-checkbox.tsx
> +     * The checkbox name
I think this description needs changed

2021-07-28 16:16 UTC, micahjones13 commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop({ reflect: true, mutable: true }) checked = false
Does this need to be typed? ie, `checked: boolean`
If so, indeterminate and disabled would need updated as well

2021-07-28 20:12 UTC, Full-lifey requested changes
Indeterminate state still functioning differently than standard. It goes from appearing indeterminate to then unchecked and then back to indeterminate.

Usually indeterminate once clicked will then go to a checked state. Once clicked further it will toggle normally between unchecked and checked.

2021-07-28 20:19 UTC, markacianfrani requested changes
light theme regressions failing

2021-07-28 21:32 UTC, Full-lifey approved these changes
Approving. Shasha created a ticket for indeterminate functionality in ASTRO-1604

2021-07-28 21:57 UTC, micahjones13 approved these changes
Approving, but curious on the invalid prop and it's necessity / how it's being used.

2021-07-28 21:57 UTC, micahjones13 commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop() invalid: boolean = false
Is this ever doing anything? I can see that it determines a div, but that div isn't styled any differently to signal that the checkbox is invalid.

2021-07-28 22:19 UTC, Cheshire89 commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop() invalid: boolean = false
its sets error styling 'rux-checkbox--invalid': invalid,

2021-07-28 22:28 UTC, micahjones13 commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop() invalid: boolean = false
There isn't any mention of invalid in the scss file, which is why I'm a bit confused as to what it's doing

2021-07-28 23:19 UTC, markacianfrani commented on src/components/rux-checkbox/rux-checkbox.tsx
> +    @Prop() invalid: boolean = false
Agreed this should be addressed. Created ASTRO-1606

2021-07-28 23:19 UTC, markacianfrani approved these changes

2021-07-29 00:23 UTC, merged