Astro 1591 e2e test setup
RocketCommunicationsInc/astro-components-stencil pull request #77
Opened 2021-07-23 18:45 UTC by markacianfrani

## Brief Description

Migrate to Cypress for E2E Testing

## JIRA Link

[ASTRO-1591](https://rocketcom.atlassian.net/browse/ASTRO-1591)

## General Notes
* Replaces npm-run-all with concurrently. I couldn't figure out how to run node commands that weren't npm scripts.

## Motivation and Context

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [ ] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2021-07-23 19:42 UTC, micahjones13 requested changes

2021-07-23 19:42 UTC, micahjones13 commented on src/components/rux-notification/test/rux-notification.e2e.js
> +    //   it('closes after time is up', async () => {
Could you elaborate more on why we don't include the other tests, and instead just have the basic render tests? If cypress supports these js tests, I feel like the more coverage the better. Maybe I'm misunderstanding something?

2021-07-23 19:42 UTC, micahjones13 commented on src/components/rux-tabs/test/rux-tabs.e2e.js
> +        cy.visitStory('components-tabs--default-story')
This one is seemingly opposite - no renders test, but all of the others

2021-07-23 19:42 UTC, micahjones13 commented on src/components/rux-tree/test/rux-tree.e2e.ts
> -    it('focuses first node', async () => {
Was this test omitted for any reason?

2021-07-23 19:47 UTC, markacianfrani commented on src/components/rux-notification/test/rux-notification.e2e.js
> +    //   it('closes after time is up', async () => {
absolutely! we'll definitely be adding more in separate tickets. This PR is just to get the foundation up and running and provide some basic examples.

2021-07-23 20:02 UTC, markacianfrani commented on src/components/rux-tree/test/rux-tree.e2e.ts
> -    it('focuses first node', async () => {
will be added in a bigger PR that will include more extensive Tree tests

2021-07-23 20:04 UTC, markacianfrani commented on src/components/rux-tabs/test/rux-tabs.e2e.js
> +        cy.visitStory('components-tabs--default-story')
added back in

2021-07-23 20:27 UTC, micahjones13 approved these changes

2021-07-26 17:21 UTC, nortonprojects commented on package.json
> +        "test.regression": "concurrently \"npm run start\" \"npm run storybook\"",
Both `concurrently` and `npm-run-all` are used in here, it looks like one of them can be gotten rid of.

2021-07-26 17:25 UTC, nortonprojects requested changes
Once `concurrently` or `npm-run-all` are chosen, this will be good.

I prefer to get rid of example files, but that's not something that should hold up the PR at this point

2021-07-26 18:50 UTC, markacianfrani commented on cypress/plugins/index.js
> +/// <reference types="cypress" />
nope removed

2021-07-26 18:52 UTC, markacianfrani commented on package.json
> +        "test.regression": "concurrently \"npm run start\" \"npm run storybook\"",
removed npm run all in favor of concurrently to avoid having to write even more one off npm scripts

2021-07-26 19:19 UTC, nortonprojects approved these changes

2021-07-26 20:40 UTC, merged