Husky prepush
RocketCommunicationsInc/astro-components-stencil pull request #82
Opened 2021-07-26 23:45 UTC by nortonprojects

## Brief Description

Added testing locally and with Github Actions as an automated step.

Instead of running them at commit-time, when code may not be ready for tests, it runs them at push-time, so it's using theoretically complete code. And it runs both locally and remotely for faster feedback and better enforcement.

## JIRA Link

N/A

## Related Issue

## General Notes

## Motivation and Context

Testing is currently a manual step that can be automated

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [X] New feature
-   [ ] Breaking change

## Checklist

-   [X] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [X] All new and existing tests passed.

2021-07-27 05:49 UTC, Cheshire89 requested changes

2021-07-27 05:49 UTC, Cheshire89 commented on .github/workflows/pr-test.yml
> +            - name: Run Jest Tests
@markacianfrani didn't we just update testing framework to use `npm run cy.test` ?

2021-07-27 12:12 UTC, markacianfrani commented on .github/workflows/pr-test.yml
> +            - name: Run Jest Tests
For E2E tests. The jest unit tests are still just npm run test

2021-07-27 12:22 UTC, markacianfrani commented
I feel like the pre push hook might be too much. I'm thinking of scenarios like resolving a package.json merge conflict or something small. Having to wait for the whole test suite to run could be annoying when I've already just ran it locally. They'll take longer and longer to run too as the project grows. We can just do git push --iforget though so it's not a huge deal. I'm down for trying it. 

The GitHub action is perfect though. 👌

2021-07-27 13:14 UTC, Full-lifey approved these changes

2021-07-27 14:43 UTC, nortonprojects commented
> I feel like the pre push hook might be too much. I'm thinking of scenarios like resolving a package.json merge conflict or something small. Having to wait for the whole test suite to run could be annoying when I've already just ran it locally. They'll take longer and longer to run too as the project grows. We can just do git push --iforget though so it's not a huge deal. I'm down for trying it.
> 
> The GitHub action is perfect though.

That's a good point. Maybe I can configure it to only run tests if relevant files have changed since the last push or something like that. That's the sort of noise I was trying to avoid having it be a pre-push instead of pre-commit, after all.

2021-07-27 14:47 UTC, nortonprojects commented
Looks like Jest has a `--changedSince` option - I'll change it to only run files changed locally, then run the full suite in the action

2021-07-28 00:36 UTC, markacianfrani approved these changes

2021-07-29 15:25 UTC, Cheshire89 approved these changes

2021-08-02 17:16 UTC, merged