Astro 1437 slider
RocketCommunicationsInc/astro-components-stencil pull request #88
Opened 2021-07-28 21:21 UTC by micahjones13

## Brief Description

Ported slider to Stencil.

## JIRA Link
https://rocketcom.atlassian.net/browse/ASTRO-1437
## Related Issue

## General Notes

Opted to remove the input box that displayed the value, and the label of the slider in favor of having more dev freedom.
From the ticket: `This component tries to do too much. The input field and title should be considered for removal enabling developers to implement as they see fit.` 

## Motivation and Context

Ports slider from lit to stencil. Simplifies the component and grants more dev freedom with the removal of the title (label) and the input box.

## Issues and Limitations
This isn't passing regressions due to the old component having labels and input fields, which have been removed from this implementation. 

In storybook, increasing/decreasing the step control does some wild stuff to the slider's thumb. 

## Types of changes

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the documentation.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

2021-07-29 22:01 UTC, markacianfrani approved these changes
Made a new ticket for the step issues - ASTRO-1628

2021-07-29 22:47 UTC, NicDominguez requested changes
Just a couple build file deletions and a few minor changes. I also found a case that breaks it but I think we should tackle it later. You could also write some unit tests for your functions if you want to go the extra mile. It's good work though and a pretty complex component.

2021-07-29 22:47 UTC, NicDominguez commented on src/components/rux-slider/rux-slider.tsx
> +        if (!this.min && this.min != 0) {
I think you can use if (isNaN(min)) {} as the check here since it counts zero as a number.

2021-07-29 22:47 UTC, NicDominguez commented on src/components/rux-slider/rux-slider.tsx
> +    //Safari needs 0px top for the thumb to look normal.
really...wow...

2021-07-29 22:47 UTC, NicDominguez commented on src/components/rux-slider/rux-slider.tsx
> +        const target = e.target as HTMLInputElement
Not sure how we want to handle this edge case but it appears that when the value is less than the step the slider has some buggy visuals. 
![image](https://user-images.githubusercontent.com/8237598/127574440-e6091154-d8a4-498f-a804-c4ad0097613a.png)
A related thing happens when the step is not a divisible factor of max, the thumb cannot go above the final whole step. 
![image](https://user-images.githubusercontent.com/8237598/127574623-57204880-9a0d-476c-80b6-1f5b8b6c0b6e.png)
You may want to limit the step values allowed or you could adjust value to be only what the step allows. Not quite sure, we may want to just create a ticket for future revision.

2021-07-30 15:27 UTC, NicDominguez approved these changes

2021-07-30 15:27 UTC, micahjones13 commented on src/components/rux-slider/rux-slider.tsx
> +        const target = e.target as HTMLInputElement
Mark has made a ticket for that [Here](https://rocketcom.atlassian.net/browse/ASTRO-1628)

2021-07-30 15:38 UTC, merged