Astro 1565 trigger pop up with custom element
RocketCommunicationsInc/astro-components-stencil pull request #91
Opened 2021-07-29 17:03 UTC by Full-lifey

## Brief Description

When the pop-up-menu is set to open on first render the positioning was not working, causing it to always render at the top left corner

## JIRA Link

[ASTRO-1565](https://rocketcom.atlassian.net/browse/ASTRO-1565?atlOrigin=eyJpIjoiZGE5ZWEyYTZlZGFhNDAxNDhhMmI2NGMzYmRhYjVjNjkiLCJwIjoiaiJ9)

## Related Issue

[ASTRO-1565](https://rocketcom.atlassian.net/browse/ASTRO-1564?atlOrigin=eyJpIjoiMDJhNjc4MjZiYWM0NDRmNWJhMGQ1NzRhZTdhNjZmMDciLCJwIjoiaiJ9)

## General Notes

## Motivation and Context

Solves a positioning bug when setting the menu open on first render

## Issues and Limitations

## Types of changes

-   [x] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

2021-07-29 17:06 UTC, Full-lifey commented on src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
> +    @State() menuBounds?: DOMRect
Moved bounding data for positioning into state to trigger re-renders when the anchor element or menu bounds change.

2021-07-29 17:06 UTC, Full-lifey commented on src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
> +    }
This is the key. Set position of the element after render

2021-07-29 17:06 UTC, Full-lifey commented on src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
> +            menuBounds = this.el.getBoundingClientRect()
Need to pull bounding data of anchor element after render or it will always come back with 0's

2021-07-29 21:05 UTC, micahjones13 requested changes
There isn't any hover state currently, although there are in designs. Probably a separate ticket. 
When switching between default and with anchors, you can see the pop up flash, as well as seeing basic text for a split second. Overall there are some funky behaviors when refreshing the page or toggling between the two pop up stories - also probably a different ticket.

2021-07-29 21:05 UTC, micahjones13 commented on src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
> +    }
Pretty sure this is what is causing the weird behavior on refresh. If it's waiting for render to complete and then setting position, I think you're going to see some weird stuff on initial loads. Again, probably a separate ticket deal.

2021-07-29 21:05 UTC, micahjones13 approved these changes

2021-07-30 13:32 UTC, markacianfrani commented
> There isn't any hover state currently, although there are in designs. Probably a separate ticket.
> When switching between default and with anchors, you can see the pop up flash, as well as seeing basic text for a split second. Overall there are some funky behaviors when refreshing the page or toggling between the two pop up stories - also probably a different ticket.

@micahjones13 are there tickets for those issues yet?

2021-07-30 13:49 UTC, markacianfrani approved these changes

2021-07-30 14:10 UTC, merged