Bug: Toggling pop up menu open with open prop
RocketCommunicationsInc/astro-components-stencil pull request #97
Opened 2021-08-02 20:16 UTC by Full-lifey

## Brief Description

The menu was not functioning properly when toggling open via the open prop.

I have moved all of the wiring of the open and close for the menu to the open prop.

## JIRA Link

[ASTRO-1564](https://rocketcom.atlassian.net/browse/ASTRO-1564?atlOrigin=eyJpIjoiNjU5MDA1MzA2YmM5NGQ5MDliZmU2N2M0MTE2MTRiZmQiLCJwIjoiaiJ9)

## Related Issue

## General Notes

## Motivation and Context

It solves a bug created when I added the open property as a feature to open and close the menu.

## Issues and Limitations

There is a potential bug with the trigger element when not assigned but used to flip the open prop.
Background: When the menu is opened a click listener is created so that when you click outside of the menu it closes. If the trigger element is clicked when the menu is open there is potential for the open prop to be flipped twice.

I have somewhat alleviated this issue by not closing the menu if the anchorEl is clicked on while it's open but I haven't found a "perfect" solution.

## Types of changes

-   [x] Bug fix
-   [ ] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

2021-08-02 20:28 UTC, Full-lifey commented on src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
> +            const anchorClick = e.composedPath().includes(this.anchorEl)
Ideally this could be a check for the trigger element. However, the example of the bug for this ticket never assigned a trigger element and only flipped the open prop with a listener.

Since the menu won't open unless an anchor is assigned this was the best check I could think of as the majority of use-cases the anchor will be the same as the trigger and the user will not want the menu to close when clicking either.

2021-08-02 20:46 UTC, Full-lifey commented on src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
> +            const anchorClick = e.composedPath().includes(this.anchorEl)
I have refactored this method to check for anchor, trigger, and menu clicks and ignore them (don't close the menu)

2021-08-02 21:45 UTC, micahjones13 requested changes
If you click on an anchor to close the pop up, it no longer closes it. Other than that this looks good to me.

2021-08-03 15:39 UTC, micahjones13 approved these changes

2021-08-03 15:41 UTC, Full-lifey commented
> If you click on an anchor to close the pop up, it no longer closes it. Other than that this looks good to me.

This was an attempt to resolve an issue where the menu closes and re-opens when clicking a trigger element that is set to flip the open prop. The issue with default behavior is resolved but the close-open behavior of clicking the trigger while the menu is open set this way this exists:

```
        <script>
            const button = document.querySelector('button')
            const menu = document.querySelector('rux-pop-up-menu')
            menu.anchorEl = button
            button.addEventListener('click', () => {
                menu.open = !menu.open
            })
        </script>
```

2021-08-03 17:07 UTC, nortonprojects commented
> > If you click on an anchor to close the pop up, it no longer closes it. Other than that this looks good to me.
> 
> This was an attempt to resolve an issue where the menu closes and re-opens when clicking a trigger element that is set to flip the open prop. The issue with default behavior is resolved but this issue still exists. NOTE: This is not the way to use the component in the documentation.
> 
> ```
>         <script>
>             const button = document.querySelector('button')
>             const menu = document.querySelector('rux-pop-up-menu')
>             menu.anchorEl = button
>             button.addEventListener('click', () => {
>                 menu.open = !menu.open
>             })
>         </script>
> ```

Can you just close after a `setTimeout` or something avoid doubling it? Or instead of having the menu prop accessed directly, have it be an `open` method and an `isOpen` prop?

2021-08-03 21:01 UTC, Full-lifey commented
> > > If you click on an anchor to close the pop up, it no longer closes it. Other than that this looks good to me.
> > 
> > 
> > This was an attempt to resolve an issue where the menu closes and re-opens when clicking a trigger element that is set to flip the open prop. The issue with default behavior is resolved but this issue still exists. NOTE: This is not the way to use the component in the documentation.
> > ```
> >         <script>
> >             const button = document.querySelector('button')
> >             const menu = document.querySelector('rux-pop-up-menu')
> >             menu.anchorEl = button
> >             button.addEventListener('click', () => {
> >                 menu.open = !menu.open
> >             })
> >         </script>
> > ```
> 
> Can you just close after a `setTimeout` or something avoid doubling it? Or instead of having the menu prop accessed directly, have it be an `open` method and an `isOpen` prop?

I have thought about a setTimeout but thats a last-ditch band aid that I would prefer to avoid at all costs.

Actually, we do have an open method and an isOpen method already. I thought about removing the open property and moving it to state but I didn't want to do that without talking to the team.

2021-08-04 14:30 UTC, markacianfrani commented on src/components/rux-pop-up-menu/rux-pop-up-menu.tsx
> +            return Promise.resolve(false)
nit: async always returns a promise so you shouldn't need Promise.resolve here.

2021-08-04 16:21 UTC, markacianfrani approved these changes

2021-08-04 18:25 UTC, merged